import fixture from "@/data/processed/open-crm-fixtures.json";
import type {
  ActivityEvent,
  BusinessAccount,
  Connection,
  ConnectorDependency,
  EvidenceProbe,
  FieldMapping,
  FleetRelease,
  FleetTenant,
  Incident,
  IncidentFingerprint,
  IncidentSignatureRule,
  IntegrationFlow,
  JobTrace,
  OperationalInsights,
  QuarantineRecord,
  RawExecutionEvent,
  RecordEvidence,
  SyncJob,
  SupportTask,
  Tenant,
  WorkspaceSnapshot,
} from "@/lib/types";
import {
  classifyIncidentFingerprint,
  evaluateExposureDecision,
  EXPOSURE_POLICY_VERSION,
} from "@/lib/exposure-engine";
import {
  buildFleetMetrics,
  buildRecoveryPlans,
  buildRecoveryValueMetrics,
  incidentPolicyFields,
  recoveryPolicyCatalog,
} from "@/lib/fleet-policy";

type SourceContact = {
  id: string;
  sourceRef: string;
  fullName: string;
  accountName: string | null;
  email: string | null;
  phoneRaw: string | null;
  phoneE164: string | null;
  reservationStatus: string | null;
  issues: string[];
};

const sourceContacts = fixture.salesforce.contacts as SourceContact[];
const missingStatusContacts = sourceContacts.filter((contact) =>
  contact.issues.includes("missing_reservation_status"),
);
const reservationContactRefs = new Set(
  fixture.salesforce.reservations.map((reservation) => reservation.contactRef),
);
const noReservationControlContacts = sourceContacts.filter(
  (contact) =>
    !reservationContactRefs.has(contact.sourceRef) &&
    contact.reservationStatus === "Not Started",
);
const farscapeContact = sourceContacts.find(
  (contact) => contact.accountName === "Farscape Inc.",
);

if (!farscapeContact) {
  throw new Error("The pinned Easy Spaces fixture is missing Farscape Inc.");
}

export const seedTenant: Tenant = {
  id: "tenant-easy-spaces",
  name: "Easy Spaces",
  plan: "Enterprise",
  segment: "Event management SaaS",
  owner: "Jordan Lee",
  health: "warning",
  openIncidents: 5,
  sourceRecordCount: fixture.quality.totalRecords,
};

export const seedFleetTenants: FleetTenant[] = [
  {
    ...seedTenant,
    cohort: "Canary",
    activeConnectorVersion: "slack-4.3.0",
    targetConnectorVersion: "slack-4.4.0",
    rolloutStatus: "Pending",
    lastHealthCheck: "Awaiting canary",
    scenarioData: "180 business records from the Salesforce Easy Spaces CC0 sample app.",
  },
  {
    id: "tenant-northstar-health",
    name: "Northstar Health",
    plan: "Enterprise",
    segment: "Healthcare SaaS",
    owner: "Morgan Chen",
    health: "healthy",
    openIncidents: 0,
    sourceRecordCount: 0,
    cohort: "Early access",
    activeConnectorVersion: "slack-4.3.0",
    targetConnectorVersion: "slack-4.4.0",
    rolloutStatus: "Pending",
    lastHealthCheck: "2026-07-28T15:58:00.000Z",
    scenarioData: "Connector settings only; no business records are included.",
  },
  {
    id: "tenant-brightline-labs",
    name: "Brightline Labs",
    plan: "Growth",
    segment: "Developer tools",
    owner: "Taylor Brooks",
    health: "healthy",
    openIncidents: 0,
    sourceRecordCount: 0,
    cohort: "Stable",
    activeConnectorVersion: "slack-4.3.0",
    targetConnectorVersion: "slack-4.4.0",
    rolloutStatus: "Pending",
    lastHealthCheck: "2026-07-28T15:55:00.000Z",
    scenarioData: "Connector settings only; no business records are included.",
  },
  {
    id: "tenant-harbor-retail",
    name: "Harbor Retail",
    plan: "Growth",
    segment: "Retail operations",
    owner: "Sam Rivera",
    health: "warning",
    openIncidents: 0,
    sourceRecordCount: 0,
    cohort: "Early access",
    activeConnectorVersion: "slack-4.3.0",
    targetConnectorVersion: "slack-4.4.0",
    rolloutStatus: "Held for review",
    lastHealthCheck: "Dependency evidence is stale; promotion is blocked",
    scenarioData: "Connector settings only; no business records are included.",
  },
];

export const seedConnectorDependencies: ConnectorDependency[] = [
  {
    id: "dep-easy-spaces-slack-risk-digest",
    tenantId: "tenant-easy-spaces",
    tenantName: "Easy Spaces",
    workflowId: "flow-slack-risk-digest",
    workflowName: "Daily customer risk digest",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capabilities: ["file_upload", "message_delivery"],
    endpoints: ["files.upload", "chat.postMessage"],
    enabled: true,
    metadataStatus: "Verified",
    lastVerifiedAt: "2026-07-28T16:02:04.000Z",
    nextRunAt: "2026-07-29T16:00:00.000Z",
    criticality: "High",
    configRevision: "cfg-easy-risk-digest-v3",
  },
  {
    id: "dep-easy-spaces-slack-alerts",
    tenantId: "tenant-easy-spaces",
    tenantName: "Easy Spaces",
    workflowId: "flow-slack-customer-alerts",
    workflowName: "Customer health alerts",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capabilities: ["message_delivery"],
    endpoints: ["chat.postMessage"],
    enabled: true,
    metadataStatus: "Verified",
    lastVerifiedAt: "2026-07-28T15:57:41.000Z",
    nextRunAt: "2026-07-28T17:00:00.000Z",
    criticality: "Medium",
    configRevision: "cfg-easy-alerts-v8",
  },
  {
    id: "dep-northstar-slack-risk-digest",
    tenantId: "tenant-northstar-health",
    tenantName: "Northstar Health",
    workflowId: "flow-northstar-risk-digest",
    workflowName: "Daily customer risk digest",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capabilities: ["file_upload", "message_delivery"],
    endpoints: ["files.upload", "chat.postMessage"],
    enabled: true,
    metadataStatus: "Verified",
    lastVerifiedAt: "2026-07-28T15:58:19.000Z",
    nextRunAt: "2026-07-29T15:30:00.000Z",
    criticality: "High",
    configRevision: "cfg-northstar-risk-digest-v12",
  },
  {
    id: "dep-brightline-slack-alerts",
    tenantId: "tenant-brightline-labs",
    tenantName: "Brightline Labs",
    workflowId: "flow-brightline-customer-alerts",
    workflowName: "Customer risk alerts",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capabilities: ["message_delivery"],
    endpoints: ["chat.postMessage"],
    enabled: true,
    metadataStatus: "Verified",
    lastVerifiedAt: "2026-07-28T15:55:02.000Z",
    nextRunAt: "2026-07-29T17:00:00.000Z",
    criticality: "Medium",
    configRevision: "cfg-brightline-alerts-v5",
  },
  {
    id: "dep-harbor-slack-digest",
    tenantId: "tenant-harbor-retail",
    tenantName: "Harbor Retail",
    workflowId: "flow-harbor-weekly-digest",
    workflowName: "Weekly customer risk digest",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capabilities: [],
    endpoints: [],
    enabled: true,
    metadataStatus: "Stale",
    lastVerifiedAt: "2026-06-19T18:14:00.000Z",
    nextRunAt: "2026-08-04T16:00:00.000Z",
    criticality: "Low",
    configRevision: "cfg-harbor-weekly-v2",
  },
];

export const seedExecutionEvents: RawExecutionEvent[] = [
  {
    id: "evt-easy-files-upload-failed",
    incidentId: "inc-api-001",
    tenantId: "tenant-easy-spaces",
    dependencyId: "dep-easy-spaces-slack-risk-digest",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capability: "file_upload",
    endpoint: "files.upload",
    errorCode: "method_deprecated",
    traceId: "trace-slack-7f91",
    spanId: "span-files-upload-03",
    status: "Failed",
    observedAt: "2026-07-28T16:02:04.000Z",
  },
  {
    id: "evt-northstar-files-upload-succeeded",
    incidentId: null,
    tenantId: "tenant-northstar-health",
    dependencyId: "dep-northstar-slack-risk-digest",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capability: "file_upload",
    endpoint: "files.upload",
    errorCode: null,
    traceId: "trace-slack-913c",
    spanId: "span-files-upload-01",
    status: "Succeeded",
    observedAt: "2026-07-28T15:58:19.000Z",
  },
  {
    id: "evt-easy-alert-message-succeeded",
    incidentId: null,
    tenantId: "tenant-easy-spaces",
    dependencyId: "dep-easy-spaces-slack-alerts",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capability: "message_delivery",
    endpoint: "chat.postMessage",
    errorCode: null,
    traceId: "trace-slack-5aa2",
    spanId: "span-chat-post-11",
    status: "Succeeded",
    observedAt: "2026-07-28T15:57:41.000Z",
  },
  {
    id: "evt-brightline-message-succeeded",
    incidentId: null,
    tenantId: "tenant-brightline-labs",
    dependencyId: "dep-brightline-slack-alerts",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capability: "message_delivery",
    endpoint: "chat.postMessage",
    errorCode: null,
    traceId: "trace-slack-a77e",
    spanId: "span-chat-post-07",
    status: "Succeeded",
    observedAt: "2026-07-28T15:55:02.000Z",
  },
  {
    id: "evt-historical-files-upload-failed",
    incidentId: null,
    tenantId: "tenant-northstar-health",
    dependencyId: "dep-northstar-slack-risk-digest",
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    connectorVersion: "slack-4.3.0",
    capability: "file_upload",
    endpoint: "files.upload",
    errorCode: "method_deprecated",
    traceId: "trace-slack-historical",
    spanId: "span-files-upload-old",
    status: "Failed",
    observedAt: "2026-07-28T15:30:00.000Z",
  },
];

export const seedIncidentSignatureRules: IncidentSignatureRule[] = [
  {
    id: "slack-files-upload-retired",
    policyVersion: EXPOSURE_POLICY_VERSION,
    provider: "Slack",
    connectorFamily: "slack-risk-digest",
    errorCodes: ["method_deprecated"],
    endpoint: "files.upload",
    capability: "file_upload",
    classification: "Provider capability retired",
    vulnerableVersionRange: "<4.4.0",
    correlationWindowMinutes: 10,
  },
];

const slackFingerprint = classifyIncidentFingerprint({
  incidentId: "inc-api-001",
  events: seedExecutionEvents,
  rules: seedIncidentSignatureRules,
  evaluatedAt: "2026-07-28T16:07:28.000Z",
});

if (!slackFingerprint) {
  throw new Error("The Slack provider-change fixture did not produce a fingerprint.");
}

export const seedIncidentFingerprints: Record<string, IncidentFingerprint> = {
  "inc-api-001": slackFingerprint,
};

export const seedExposureDecisions = {
  "inc-api-001": evaluateExposureDecision({
    incidentId: "inc-api-001",
    fingerprint: slackFingerprint,
    dependencies: seedConnectorDependencies,
    events: seedExecutionEvents,
    evaluatedAt: "2026-07-28T16:07:28.000Z",
  }),
};

export const seedFleetRelease: FleetRelease = {
  id: "release-slack-440",
  provider: "Slack",
  connector: "Slack risk digest",
  fromVersion: "slack-4.3.0",
  toVersion: "slack-4.4.0",
  fallbackVersion: "slack-4.3.1-text-only",
  status: "Ready for canary",
  stageIndex: 0,
  requiredHealthyRuns: 2,
  observedHealthyRuns: 0,
  rollbackReason: null,
  updatedAt: "2026-07-28T16:07:28.000Z",
  targets: structuredClone(seedFleetTenants),
  healthPolicy: {
    version: "fleet-health-gate-v1",
    requiredRuns: 2,
    minimumSuccessRate: 0.995,
    maximumErrorRate: 0.005,
    maximumP95LatencyMs: 2500,
    maximumDuplicateWrites: 0,
  },
  healthEvidence: [],
};

export const seedSupportTasks: SupportTask[] = [
  {
    id: "support-task-slack-easy-spaces",
    fleetIncidentId: "fleet-incident-slack-upload-001",
    incidentId: "inc-api-001",
    tenantId: seedTenant.id,
    tenantName: seedTenant.name,
    status: "Unassigned",
    assignee: null,
    acknowledgedAt: null,
    lastUpdateAt: null,
    nextUpdateBy: "2026-07-28T16:50:00.000Z",
    resolvedAt: null,
    updatedAt: "2026-07-28T16:07:28.000Z",
    slaStatus: "On track",
    slaReason: "Initial impact update is due within the response window.",
  },
];

export const seedEvidenceProbes: EvidenceProbe[] = [
  {
    id: "probe-harbor-slack-01",
    incidentId: "inc-api-001",
    dependencyId: "dep-harbor-slack-digest",
    status: "Failed",
    attempt: 1,
    source: "Dependency inventory probe",
    traceId: "trace-probe-harbor-01",
    requestedBy: "Exposure worker",
    requestedAt: "2026-07-28T16:07:29.000Z",
    completedAt: "2026-07-28T16:07:31.000Z",
    failureReason: "Provider metadata request timed out; the previous dependency snapshot was preserved.",
    result: null,
    updatedAt: "2026-07-28T16:07:31.000Z",
  },
];

export const seedQuarantineRecords: QuarantineRecord[] = missingStatusContacts.map(
  (contact, index) => ({
    id: `quarantine-${String(index + 1).padStart(2, "0")}`,
    incidentId: "inc-data-001",
    tenantId: seedTenant.id,
    sourceRecordId: contact.id,
    label: contact.fullName,
    status: "Quarantined",
    reason: "Reservation_Status__c is required",
    checkpoint: `Contact:${contact.id}`,
    idempotencyKey: `easy-spaces:contacts:${contact.id}:2026-07-28T16:15`,
    replayAttemptId: null,
    updatedAt: "2026-07-28T16:26:14.000Z",
  }),
);

export const seedAccounts: BusinessAccount[] = fixture.salesforce.accounts.map(
  (account) => ({
    id: account.id,
    name: account.name,
    phone: null,
    website: null,
    source: "Salesforce Easy Spaces",
  }),
);

export const seedConnections: Connection[] = [
  {
    id: "conn-salesforce",
    tenantId: seedTenant.id,
    provider: "Salesforce",
    category: "CRM source",
    direction: "Source",
    status: "warning",
    authStatus: "Connected",
    owner: "Easy Spaces admin",
    lastSync: "2026-07-28T16:26:00.000Z",
    openIncidents: 2,
    scopes: "api, refresh_token, offline_access",
    nextAction: "Review one source value and one mapping",
    lastVerified: "2026-07-28T16:12:00.000Z",
  },
  {
    id: "conn-hubspot",
    tenantId: seedTenant.id,
    provider: "HubSpot",
    category: "CRM source",
    direction: "Source",
    status: "broken",
    authStatus: "Reconnect required",
    owner: "Easy Spaces admin",
    lastSync: "2026-07-28T14:18:00.000Z",
    openIncidents: 1,
    scopes: "crm.objects.contacts.read, oauth",
    nextAction: "Easy Spaces admin must reconnect",
    lastVerified: "2026-07-28T16:18:00.000Z",
  },
  {
    id: "conn-customer-360",
    tenantId: seedTenant.id,
    provider: "Customer 360",
    category: "Customer success workspace",
    direction: "Internal",
    status: "healthy",
    authStatus: "Internal service",
    owner: "Integration platform",
    lastSync: "2026-07-28T16:34:00.000Z",
    openIncidents: 0,
    scopes: "tenant.write, health.read",
    nextAction: "No action needed",
    lastVerified: "2026-07-28T16:34:00.000Z",
  },
  {
    id: "conn-sheets",
    tenantId: seedTenant.id,
    provider: "Google Sheets",
    category: "Health report export",
    direction: "Destination",
    status: "warning",
    authStatus: "Connected",
    owner: "Integration platform",
    lastSync: "2026-07-28T16:31:00.000Z",
    openIncidents: 1,
    scopes: "spreadsheets",
    nextAction: "System backoff is scheduled",
    lastVerified: "2026-07-28T16:31:00.000Z",
  },
  {
    id: "conn-slack",
    tenantId: seedTenant.id,
    provider: "Slack",
    category: "Customer risk notification",
    direction: "Destination",
    status: "broken",
    authStatus: "Connected",
    owner: "Integration engineering",
    lastSync: "2026-07-28T16:02:00.000Z",
    openIncidents: 1,
    scopes: "chat:write, files:write",
    nextAction: "Deploy the external upload sequence",
    lastVerified: "OAuth token valid; endpoint is retired",
  },
];

export const seedFlows: IntegrationFlow[] = [
  {
    id: "flow-contact-health",
    tenantId: seedTenant.id,
    name: "Salesforce contacts to Customer 360",
    sourceConnectionId: "conn-salesforce",
    destinationConnectionId: "conn-customer-360",
    sourceObject: "Contact",
    destinationObject: "Customer profile",
    direction: "One-way",
    schedule: "Every 15 minutes",
    status: "warning",
    mappingVersion: "v4.2",
    schemaVersion: "2026-06",
    retryPolicy: "3 attempts, exponential backoff",
    ownerTeam: "Integration platform",
    lastRunAt: "2026-07-28T16:26:00.000Z",
    nextRunAt: "2026-07-28T16:41:00.000Z",
    description:
      "Keeps Customer 360 profiles current for health scoring and success workflows.",
    identityRule:
      "Salesforce Contact ID is primary; normalized email is the secondary match key.",
  },
  {
    id: "flow-hubspot-contacts",
    tenantId: seedTenant.id,
    name: "HubSpot contacts to Customer 360",
    sourceConnectionId: "conn-hubspot",
    destinationConnectionId: "conn-customer-360",
    sourceObject: "Contact",
    destinationObject: "Customer profile",
    direction: "One-way",
    schedule: "Every 30 minutes",
    status: "broken",
    mappingVersion: "v2.8",
    schemaVersion: "2026-05",
    retryPolicy: "Resume after OAuth verification",
    ownerTeam: "Integration platform",
    lastRunAt: "2026-07-28T14:18:00.000Z",
    nextRunAt: "Paused",
    description:
      "Imports marketing contacts for accounts that use HubSpot as a secondary CRM.",
    identityRule:
      "Match by normalized email; Salesforce remains authoritative for account ownership.",
  },
  {
    id: "flow-reservation-lifecycle",
    tenantId: seedTenant.id,
    name: "Salesforce reservations to lifecycle",
    sourceConnectionId: "conn-salesforce",
    destinationConnectionId: "conn-customer-360",
    sourceObject: "Reservation__c",
    destinationObject: "Lifecycle event",
    direction: "One-way",
    schedule: "Every 15 minutes",
    status: "warning",
    mappingVersion: "v6.0",
    schemaVersion: "2026-07",
    retryPolicy: "3 attempts, then engineering review",
    ownerTeam: "Integration engineering",
    lastRunAt: "2026-07-28T16:22:00.000Z",
    nextRunAt: "Awaiting mapping",
    description:
      "Turns reservation changes into lifecycle signals used by Customer Success.",
    identityRule:
      "Salesforce Reservation__c ID identifies each lifecycle event.",
  },
  {
    id: "flow-weekly-health",
    tenantId: seedTenant.id,
    name: "Customer health to Google Sheets",
    sourceConnectionId: "conn-customer-360",
    destinationConnectionId: "conn-sheets",
    sourceObject: "Account health",
    destinationObject: "Weekly health report",
    direction: "One-way",
    schedule: "Every Monday at 8:00 AM",
    status: "warning",
    mappingVersion: "v3.4",
    schemaVersion: "2026-06",
    retryPolicy: "Truncated exponential backoff",
    ownerTeam: "Integration platform",
    lastRunAt: "2026-07-28T16:31:00.000Z",
    nextRunAt: "Retry in 30 seconds",
    description:
      "Exports health and risk signals for Easy Spaces' weekly operating review.",
    identityRule:
      "Customer 360 account ID provides one stable row key per account.",
  },
  {
    id: "flow-slack-risk-digest",
    tenantId: seedTenant.id,
    name: "Customer risk digest to Slack",
    sourceConnectionId: "conn-customer-360",
    destinationConnectionId: "conn-slack",
    sourceObject: "Risk digest",
    destinationObject: "Slack file and message",
    direction: "One-way",
    schedule: "Weekdays at 9:00 AM",
    status: "broken",
    mappingVersion: "v1.9",
    schemaVersion: "2026-04",
    retryPolicy: "Blocked until connector patch",
    ownerTeam: "Integration engineering",
    lastRunAt: "2026-07-28T16:02:00.000Z",
    nextRunAt: "Awaiting connector patch",
    description:
      "Posts a CSV risk digest and summary to the Customer Success Slack channel.",
    identityRule:
      "Customer 360 account ID prevents duplicate accounts in each digest.",
  },
];

export const seedMappings: FieldMapping[] = [
  {
    id: "map-contact-status",
    tenantId: seedTenant.id,
    flowId: "flow-contact-health",
    connectionId: "conn-salesforce",
    relatedIncidentId: "inc-data-001",
    sourceObject: "Contact",
    sourceField: "Reservation_Status__c",
    destinationField: "reservation_status",
    dataType: "Picklist -> enum",
    required: true,
    confidence: 96,
    status: "Mapped",
    transform: "Use source value",
    transformOptions: ["Use source value", "Default missing values"],
    rawSample: "",
    cleanedSample: "Not Started",
    affectedRecords: missingStatusContacts.length,
  },
  {
    id: "map-reservation-lifecycle",
    tenantId: seedTenant.id,
    flowId: "flow-reservation-lifecycle",
    connectionId: "conn-salesforce",
    relatedIncidentId: "inc-map-001",
    sourceObject: "Reservation__c",
    sourceField: "Status__c",
    destinationField: "lifecycle_stage",
    dataType: "Picklist -> enum",
    required: true,
    confidence: 61,
    status: "Review",
    transform: "Direct mapping",
    transformOptions: [
      "Direct mapping",
      "Map Draft to Planning",
      "Normalize lifecycle values",
    ],
    rawSample: "Draft",
    cleanedSample: "Planning",
    affectedRecords: 2,
  },
  {
    id: "map-account-name",
    tenantId: seedTenant.id,
    flowId: "flow-contact-health",
    connectionId: "conn-salesforce",
    relatedIncidentId: null,
    sourceObject: "Account",
    sourceField: "Name",
    destinationField: "account_name",
    dataType: "String",
    required: true,
    confidence: 100,
    status: "Mapped",
    transform: "Trim whitespace",
    transformOptions: ["Trim whitespace"],
    rawSample: "Farscape Inc.",
    cleanedSample: "Farscape Inc.",
    affectedRecords: 12,
  },
  {
    id: "map-health-score",
    tenantId: seedTenant.id,
    flowId: "flow-weekly-health",
    connectionId: "conn-sheets",
    relatedIncidentId: null,
    sourceObject: "Account health",
    sourceField: "health_score",
    destinationField: "Health Score",
    dataType: "Number",
    required: true,
    confidence: 100,
    status: "Mapped",
    transform: "Round to integer",
    transformOptions: ["Round to integer"],
    rawSample: "78.4",
    cleanedSample: "78",
    affectedRecords: 12,
  },
  {
    id: "map-risk-reason",
    tenantId: seedTenant.id,
    flowId: "flow-slack-risk-digest",
    connectionId: "conn-slack",
    relatedIncidentId: null,
    sourceObject: "Risk digest",
    sourceField: "risk_reason",
    destinationField: "CSV: Risk reason",
    dataType: "String",
    required: true,
    confidence: 100,
    status: "Mapped",
    transform: "Escape CSV value",
    transformOptions: ["Escape CSV value"],
    rawSample: "Usage declined, renewal in 45 days",
    cleanedSample: '"Usage declined, renewal in 45 days"',
    affectedRecords: 4,
  },
];

const incidentScenarios: Incident[] = [
  {
    id: "inc-data-001",
    tenantId: seedTenant.id,
    flowId: "flow-contact-health",
    jobId: "job-data-001",
    connectionId: "conn-salesforce",
    type: "data_quality",
    title: "Reservation status is missing",
    summary:
      "A required source value is blank on six Salesforce contacts. The customer controls whether a source default may be applied.",
    severity: "Medium",
    status: "Awaiting customer",
    disposition: null,
    owner: "Customer admin",
    detectedAt: "2026-07-28T16:26:14.000Z",
    classifiedAt: "2026-07-28T16:28:02.000Z",
    updatedAt: "2026-07-28T16:28:02.000Z",
    impact: "6 of 12 customer profiles are missing reservation status.",
    affectedRecords: missingStatusContacts.length,
    actionState: "Customer review required",
    step: 0,
    runbook:
      "Review the relationship evidence, then approve the scoped default or keep the records quarantined.",
    providerCode: "required_field_missing",
    providerReferenceUrl: null,
    customerVisible: true,
    customerTitle: "Complete missing Salesforce reservation statuses",
    customerSummary:
      "Six Salesforce contacts need a reservation status before their profiles can update.",
    recoveryMode: "Customer action required",
    ownerReason:
      "Only the Easy Spaces admin may approve how its source CRM values are handled.",
    actionRequired:
      "Approve the suggested default or keep the six records quarantined.",
    automaticNextStep:
      "The platform validates the decision and retries only records eligible for replay.",
    escalationCondition:
      "Support is notified only if the records remain unchanged past the customer response window.",
    nextUpdateBy: "After Easy Spaces submits the corrections",
    supportEngagement: "Watching",
    supportNote:
      "Track the customer decision. Support should not approve CRM data changes for the customer.",
    resolution: null,
    mappingVersion: "v4.2",
    connectorVersion: "salesforce-3.7.1",
  },
  {
    id: "inc-auth-001",
    tenantId: seedTenant.id,
    flowId: "flow-hubspot-contacts",
    jobId: "job-auth-001",
    connectionId: "conn-hubspot",
    type: "authentication",
    title: "HubSpot authorization expired",
    summary:
      "The refresh token was rejected. Only an Easy Spaces admin can grant access again.",
    severity: "High",
    status: "Awaiting customer",
    disposition: null,
    owner: "Customer admin",
    detectedAt: "2026-07-28T14:18:06.000Z",
    classifiedAt: "2026-07-28T14:19:41.000Z",
    updatedAt: "2026-07-28T14:19:41.000Z",
    impact:
      "The scheduled HubSpot contact sync is paused. Authentication failed before provider records were read.",
    affectedRecords: 0,
    actionState: "Reconnect required",
    step: 0,
    runbook: "Reconnect HubSpot, verify scopes, then resume from the checkpoint.",
    providerCode: "invalid_grant",
    providerReferenceUrl: "https://developers.hubspot.com/docs/guides/apps/authentication/oauth-quickstart-guide",
    customerVisible: true,
    customerTitle: "Reconnect HubSpot",
    customerSummary:
      "HubSpot access expired before any contact data was read. Reconnect the same account to resume sync.",
    recoveryMode: "Customer action required",
    ownerReason:
      "OAuth consent must be granted by an administrator in the customer organization.",
    actionRequired: "Reconnect HubSpot and approve the required contact scope.",
    automaticNextStep:
      "The platform will verify tenant identity and scopes, then resume from the checkpoint.",
    escalationCondition:
      "Support is notified if authorization is not restored before the next scheduled sync.",
    nextUpdateBy: "Immediately after authorization returns",
    supportEngagement: "Watching",
    supportNote: "Explain why reconnect is needed and monitor recovery.",
    resolution: null,
    mappingVersion: "v2.8",
    connectorVersion: "hubspot-2.5.0",
  },
  {
    id: "inc-map-001",
    tenantId: seedTenant.id,
    flowId: "flow-reservation-lifecycle",
    jobId: "job-map-001",
    connectionId: "conn-salesforce",
    type: "mapping",
    title: "Draft is not a valid lifecycle stage",
    summary:
      "The source added a value that the destination enum does not accept. Engineering owns the mapping contract.",
    severity: "Medium",
    status: "Awaiting engineering",
    disposition: null,
    owner: "Integration engineer",
    detectedAt: "2026-07-28T16:22:37.000Z",
    classifiedAt: "2026-07-28T16:24:16.000Z",
    updatedAt: "2026-07-28T16:24:16.000Z",
    impact: "2 reservation events are blocked from Customer 360.",
    affectedRecords: 2,
    actionState: "Mapping change required",
    step: 0,
    runbook: "Preview the transform against samples and publish a new mapping version.",
    providerCode: "destination_enum_rejected",
    providerReferenceUrl: null,
    customerVisible: false,
    customerTitle: "Reservation updates delayed",
    customerSummary:
      "The platform is updating an internal field rule. No customer action is required.",
    recoveryMode: "Engineering action required",
    ownerReason:
      "The rejected enum is owned by the platform mapping contract, not customer source data.",
    actionRequired:
      "Publish a scoped mapping after sample and contract checks pass.",
    automaticNextStep:
      "The platform will validate the release, retry two blocked events, and watch for repeat failures.",
    escalationCondition:
      "Roll back to v6.0 if any contract case fails or failures appear outside this tenant.",
    nextUpdateBy: "After mapping validation completes",
    supportEngagement: "Not involved",
    supportNote: "No customer action is needed. Share status only if the delay grows.",
    resolution: null,
    mappingVersion: "v6.0",
    connectorVersion: "salesforce-3.7.1",
  },
  {
    id: "inc-rate-001",
    tenantId: seedTenant.id,
    flowId: "flow-weekly-health",
    jobId: "job-rate-001",
    connectionId: "conn-sheets",
    type: "rate_limit",
    title: "Google Sheets write quota reached",
    summary:
      "The provider returned HTTP 429. The system scheduled a retry after backoff.",
    severity: "Low",
    status: "Backoff scheduled",
    disposition: null,
    owner: "System",
    detectedAt: "2026-07-28T16:31:11.000Z",
    classifiedAt: "2026-07-28T16:31:16.000Z",
    updatedAt: "2026-07-28T16:31:16.000Z",
    impact: "The weekly report is delayed; no records are lost.",
    affectedRecords: 12,
    actionState: "Retry in 30 seconds",
    step: 0,
    runbook: "Wait for the scheduled retry. Escalate only after the retry budget is exhausted.",
    providerCode: "429 RESOURCE_EXHAUSTED",
    providerReferenceUrl: "https://developers.google.com/workspace/sheets/api/limits",
    customerVisible: false,
    customerTitle: "Weekly report delayed",
    customerSummary:
      "The platform is retrying the Google Sheets export automatically. No action is required.",
    recoveryMode: "System managed",
    ownerReason:
      "HTTP 429 is a transient provider response covered by the retry policy.",
    actionRequired: "No human action.",
    automaticNextStep:
      "Retry after backoff using the same idempotency key.",
    escalationCondition:
      "Create a Support incident only if the retry budget is exhausted or the report misses its SLA.",
    nextUpdateBy: "After the scheduled retry",
    supportEngagement: "Not involved",
    supportNote: "No manual action. The system owns this recovery.",
    resolution: null,
    mappingVersion: "v3.4",
    connectorVersion: "sheets-1.8.2",
  },
  {
    id: "inc-api-001",
    tenantId: seedTenant.id,
    flowId: "flow-slack-risk-digest",
    jobId: "job-api-001",
    connectionId: "conn-slack",
    type: "provider_change",
    title: "Slack file upload endpoint is retired",
    summary:
      "The connector still calls files.upload, which Slack sunset on November 12, 2025.",
    severity: "High",
    status: "Awaiting engineering",
    disposition: null,
    owner: "Integration engineer",
    detectedAt: "2026-07-28T16:02:04.000Z",
    classifiedAt: "2026-07-28T16:07:28.000Z",
    updatedAt: "2026-07-28T16:07:28.000Z",
    impact: "The daily risk digest cannot attach its CSV report.",
    affectedRecords: 4,
    actionState: "Connector patch required",
    step: 0,
    runbook: "Test the external upload sequence, deploy it, then monitor the next run.",
    providerCode: "method_deprecated",
    providerReferenceUrl:
      "https://docs.slack.dev/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay/",
    customerVisible: true,
    customerTitle: "Daily Slack risk digest delayed",
    customerSummary:
      "Engineering is replacing a retired Slack upload method. Your team does not need to change anything.",
    recoveryMode: "Engineering action required",
    ownerReason:
      "The provider retired a connector method, so the SaaS engineering team owns recovery.",
    actionRequired:
      "Pass contract tests, release to an Easy Spaces canary, and keep rollback ready.",
    automaticNextStep:
      "The platform will evaluate two canary runs, stop promotion if a gate fails, and keep rollback available to Engineering.",
    escalationCondition:
      "Support coordinates updates because a high-impact customer deliverable is blocked.",
    nextUpdateBy: "After the canary run or within 30 minutes",
    supportEngagement: "Needs support",
    supportNote: "Keep Easy Spaces informed while engineering replaces the endpoint.",
    resolution: null,
    mappingVersion: "v1.9",
    connectorVersion: "slack-4.3.0",
  },
];

export const seedIncidents: Incident[] = incidentScenarios.map((incident) => ({
  ...incident,
  ...incidentPolicyFields(incident.type),
}));

export const seedJobs: SyncJob[] = [
  {
    id: "job-rate-001",
    tenantId: seedTenant.id,
    flowId: "flow-weekly-health",
    connectionId: "conn-sheets",
    incidentId: "inc-rate-001",
    provider: "Google Sheets",
    objectType: "Spreadsheet row",
    status: "Backoff scheduled",
    startedAt: "2026-07-28T16:31:08.000Z",
    completedAt: null,
    durationSeconds: 8,
    processed: 0,
    failed: 12,
    skipped: 0,
    checkpoint: "batch:1/1",
    errorType: "Rate limit",
    summary: "Quota exceeded; retry scheduled with jitter.",
    affectedRecordIds: seedAccounts.map((account) => account.id),
    retryOf: null,
    idempotencyKey: "easy-spaces:health-export:2026-07-28",
  },
  {
    id: "job-data-001",
    tenantId: seedTenant.id,
    flowId: "flow-contact-health",
    connectionId: "conn-salesforce",
    incidentId: "inc-data-001",
    provider: "Salesforce",
    objectType: "Contact",
    status: "Blocked",
    startedAt: "2026-07-28T16:26:10.000Z",
    completedAt: "2026-07-28T16:26:14.000Z",
    durationSeconds: 4,
    processed: 6,
    failed: missingStatusContacts.length,
    skipped: 0,
    checkpoint: "Contact:ContactRef4",
    errorType: "Data quality",
    summary: "Required reservation status is blank.",
    affectedRecordIds: missingStatusContacts.map((contact) => contact.id),
    retryOf: null,
    idempotencyKey: "easy-spaces:contacts:2026-07-28T16:15",
  },
  {
    id: "job-map-001",
    tenantId: seedTenant.id,
    flowId: "flow-reservation-lifecycle",
    connectionId: "conn-salesforce",
    incidentId: "inc-map-001",
    provider: "Salesforce",
    objectType: "Reservation__c",
    status: "Blocked",
    startedAt: "2026-07-28T16:22:31.000Z",
    completedAt: "2026-07-28T16:22:37.000Z",
    durationSeconds: 6,
    processed: 0,
    failed: 2,
    skipped: 0,
    checkpoint: "Reservation__c:Reservation__cRef1",
    errorType: "Mapping",
    summary: "Destination rejected lifecycle stage Draft.",
    affectedRecordIds: ["sf-reservation-001", "sf-reservation-002"],
    retryOf: null,
    idempotencyKey: "easy-spaces:reservations:2026-07-28T16:15",
  },
  {
    id: "job-api-001",
    tenantId: seedTenant.id,
    flowId: "flow-slack-risk-digest",
    connectionId: "conn-slack",
    incidentId: "inc-api-001",
    provider: "Slack",
    objectType: "CSV file",
    status: "Blocked",
    startedAt: "2026-07-28T16:02:01.000Z",
    completedAt: "2026-07-28T16:02:04.000Z",
    durationSeconds: 3,
    processed: 0,
    failed: 4,
    skipped: 0,
    checkpoint: "risk-digest:upload",
    errorType: "Provider API change",
    summary: "files.upload is no longer available.",
    affectedRecordIds: seedAccounts.slice(0, 4).map((account) => account.id),
    retryOf: null,
    idempotencyKey: "easy-spaces:risk-digest:2026-07-28",
  },
  {
    id: "job-auth-001",
    tenantId: seedTenant.id,
    flowId: "flow-hubspot-contacts",
    connectionId: "conn-hubspot",
    incidentId: "inc-auth-001",
    provider: "HubSpot",
    objectType: "Contact",
    status: "Blocked",
    startedAt: "2026-07-28T14:18:02.000Z",
    completedAt: "2026-07-28T14:18:06.000Z",
    durationSeconds: 4,
    processed: 0,
    failed: 31,
    skipped: 0,
    checkpoint: "contacts:after:184902",
    errorType: "Authentication",
    summary: "OAuth refresh returned invalid_grant.",
    affectedRecordIds: [],
    retryOf: null,
    idempotencyKey: "easy-spaces:hubspot:2026-07-28T14:00",
  },
  {
    id: "job-history-003",
    tenantId: seedTenant.id,
    flowId: "flow-contact-health",
    connectionId: "conn-salesforce",
    incidentId: null,
    provider: "Salesforce",
    objectType: "Contact",
    status: "Succeeded",
    startedAt: "2026-07-28T16:00:00.000Z",
    completedAt: "2026-07-28T16:00:09.000Z",
    durationSeconds: 9,
    processed: 12,
    failed: 0,
    skipped: 0,
    checkpoint: "Contact:complete",
    errorType: null,
    summary: "12 contacts synchronized.",
    affectedRecordIds: [],
    retryOf: null,
    idempotencyKey: "easy-spaces:contacts:2026-07-28T16:00",
  },
  {
    id: "job-history-002",
    tenantId: seedTenant.id,
    flowId: "flow-weekly-health",
    connectionId: "conn-sheets",
    incidentId: null,
    provider: "Google Sheets",
    objectType: "Spreadsheet row",
    status: "Succeeded",
    startedAt: "2026-07-21T15:00:00.000Z",
    completedAt: "2026-07-21T15:00:12.000Z",
    durationSeconds: 12,
    processed: 12,
    failed: 0,
    skipped: 0,
    checkpoint: "batch:complete",
    errorType: null,
    summary: "12 health rows appended.",
    affectedRecordIds: [],
    retryOf: null,
    idempotencyKey: "easy-spaces:health-export:2026-07-21",
  },
  {
    id: "job-history-001",
    tenantId: seedTenant.id,
    flowId: "flow-slack-risk-digest",
    connectionId: "conn-slack",
    incidentId: null,
    provider: "Slack",
    objectType: "CSV file",
    status: "Succeeded",
    startedAt: "2025-11-11T17:00:00.000Z",
    completedAt: "2025-11-11T17:00:07.000Z",
    durationSeconds: 7,
    processed: 3,
    failed: 0,
    skipped: 0,
    checkpoint: "risk-digest:complete",
    errorType: null,
    summary: "Risk digest uploaded before the endpoint sunset.",
    affectedRecordIds: [],
    retryOf: null,
    idempotencyKey: "easy-spaces:risk-digest:2025-11-11",
  },
];

export const seedActivity: ActivityEvent[] = [
  {
    id: 1,
    tenantId: seedTenant.id,
    incidentId: "inc-data-001",
    actorRole: "system",
    actorLabel: "Validation worker",
    action: "Classified incident",
    detail: "Routed missing source data to the Easy Spaces admin.",
    createdAt: "2026-07-28T16:28:02.000Z",
  },
  {
    id: 2,
    tenantId: seedTenant.id,
    incidentId: "inc-rate-001",
    actorRole: "system",
    actorLabel: "Retry worker",
    action: "Scheduled backoff",
    detail: "Attempt 2 will run after 30 seconds with jitter.",
    createdAt: "2026-07-28T16:31:16.000Z",
  },
];

export const evidenceByIncidentId: Record<string, RecordEvidence[]> = {
  "inc-data-001": missingStatusContacts.map((contact) => ({
    id: contact.id,
    sourceObject: "Salesforce Contact",
    label: contact.fullName,
    accountName: contact.accountName,
    field: "Reservation_Status__c",
    rawValue: "",
    cleanedValue: "Not Started",
    issue: "Required value is blank",
    provenance: "Open sample data",
    sourceLabel: "Salesforce Easy Spaces CC0 Contact record",
    businessContext: `${contact.fullName} is linked to ${contact.accountName ?? "an unassigned account"} and has no related Reservation__c record in the sample data.`,
    suggestedValue: "Not Started",
    suggestionReason: `${noReservationControlContacts.length} comparable sample contacts have no linked Reservation__c record and use Not Started. The rule applies only to blank contacts with the same relationship state.`,
    verificationRequired: "An Easy Spaces admin must approve the default before the platform applies it and rereads the source records.",
  })),
  "inc-map-001": fixture.salesforce.reservations.map((reservation) => ({
    id: reservation.id,
    sourceObject: "Salesforce Reservation__c",
    label: reservation.contactName,
    accountName: null,
    field: "Status__c -> lifecycle_stage",
    rawValue: reservation.status,
    cleanedValue: "Planning",
    issue: "Draft is not in the destination enum",
    provenance: "Open sample data",
    sourceLabel: "Salesforce Easy Spaces CC0 Reservation__c record",
    businessContext: `${reservation.contactName}'s public reservation record contains the source value ${reservation.status}.`,
    suggestedValue: "Planning",
    suggestionReason: "The scoped destination contract maps Draft to the supported Planning lifecycle value.",
    verificationRequired: "Integration Engineering must pass sample and destination-contract checks before publishing.",
  })),
  "inc-rate-001": seedAccounts.slice(0, 3).map((account) => ({
    id: account.id,
    sourceObject: "Customer 360 account",
    label: account.name,
    accountName: account.name,
    field: "Health Score",
    rawValue: "78.4",
    cleanedValue: "78",
    issue: "Record is valid; the provider quota blocked the batch",
    provenance: "Demo event",
    sourceLabel: "Demo export batch joined to a CC0 Account identifier",
    businessContext: `${account.name} is a sample account used in this export-batch demo.`,
    suggestedValue: "78",
    suggestionReason: "The export schema requires an integer; the value is normalized without changing the provider-quota diagnosis.",
    verificationRequired: "The retry must preserve the operation identity and verify one append per account.",
  })),
  "inc-api-001": seedAccounts.slice(0, 4).map((account) => ({
    id: account.id,
    sourceObject: "Customer 360 risk digest",
    label: account.name,
    accountName: account.name,
    field: "CSV attachment",
    rawValue: "risk-digest.csv",
    cleanedValue: "risk-digest.csv",
    issue: "The file is valid; the upload endpoint is retired",
    provenance: "Provider contract",
    sourceLabel: "Slack files.upload retirement demo",
    businessContext: `${account.name} appears in the risk-digest payload for this demo; its business record is not the cause of the provider failure.`,
    suggestedValue: "risk-digest.csv",
    suggestionReason: "The payload remains valid; recovery changes the connector upload sequence rather than customer data.",
    verificationRequired: "Connector contract tests and cohort health gates must pass before fleet promotion.",
  })),
  "inc-auth-001": [
    {
      id: "hubspot-connection",
      sourceObject: "HubSpot OAuth grant",
      label: "Easy Spaces production portal",
      accountName: "Easy Spaces",
      field: "refresh_token",
      rawValue: "Expired credential (redacted)",
      cleanedValue: "New grant required",
      issue: "Provider returned invalid_grant",
    provenance: "Demo event",
      sourceLabel: "OAuth failure modeled from the published auth contract",
      businessContext: "The Easy Spaces HubSpot connection failed before any contact data was read.",
      suggestedValue: "New grant required",
      suggestionReason: "The published OAuth contract requires fresh customer consent after invalid_grant.",
      verificationRequired: "The platform must verify tenant identity and crm.objects.contacts.read before resuming.",
    },
  ],
};

export const traceByIncidentId: Record<string, JobTrace> = {
  "inc-data-001": {
    correlationId: "corr-sf-7e9d13",
    requestId: "req-01J6DATA",
    idempotencyKey: "easy-spaces:contacts:2026-07-28T16:15",
    endpoint: "Salesforce Contact query -> Customer 360 /profiles:batch",
    httpStatus: 422,
    providerResponse: "required_field_missing: reservation_status",
    mappingVersion: "v4.2",
    schemaVersion: "2026-06",
    retryPolicy: "Retry after source validation",
    simulated: true,
    steps: [
      {
        stage: "Extract",
        status: "Completed",
        timestamp: "9:26:10 AM",
        detail: "12 contacts read from the Easy Spaces sample data.",
      },
      {
        stage: "Validate",
        status: "Failed",
        timestamp: "9:26:14 AM",
        detail: "6 records have a blank Reservation_Status__c.",
      },
      {
        stage: "Load",
        status: "Blocked",
        timestamp: "9:26:14 AM",
        detail: "Invalid records were quarantined; the checkpoint was retained.",
      },
    ],
  },
  "inc-auth-001": {
    correlationId: "corr-hs-a1842f",
    requestId: "req-01J6AUTH",
    idempotencyKey: "easy-spaces:hubspot:2026-07-28T14:00",
    endpoint: "POST https://api.hubapi.com/oauth/v1/token",
    httpStatus: 400,
    providerResponse: "invalid_grant: refresh token is invalid or expired",
    mappingVersion: "v2.8",
    schemaVersion: "2026-05",
    retryPolicy: "Resume after OAuth verification",
    simulated: true,
    steps: [
      {
        stage: "Refresh OAuth token",
        status: "Failed",
        timestamp: "7:18:06 AM",
        detail: "HubSpot returned invalid_grant.",
      },
      {
        stage: "Read contacts",
        status: "Blocked",
        timestamp: "7:18:06 AM",
        detail: "The worker stopped before reading customer data.",
      },
    ],
  },
  "inc-map-001": {
    correlationId: "corr-sf-8bb921",
    requestId: "req-01J6MAP",
    idempotencyKey: "easy-spaces:reservations:2026-07-28T16:15",
    endpoint: "Customer 360 POST /lifecycle-events:batch",
    httpStatus: 422,
    providerResponse: "lifecycle_stage must be one of Planning, Active, Complete",
    mappingVersion: "v6.0",
    schemaVersion: "2026-07",
    retryPolicy: "Retry after mapping publish",
    simulated: true,
    steps: [
      {
        stage: "Extract",
        status: "Completed",
        timestamp: "9:22:31 AM",
        detail: "2 Salesforce reservation records read.",
      },
      {
        stage: "Transform",
        status: "Completed",
        timestamp: "9:22:34 AM",
        detail: "Status__c Draft passed through without normalization.",
      },
      {
        stage: "Load",
        status: "Failed",
        timestamp: "9:22:37 AM",
        detail: "Customer 360 rejected the destination enum.",
      },
    ],
  },
  "inc-rate-001": {
    correlationId: "corr-gs-1f97d0",
    requestId: "req-01J6RATE",
    idempotencyKey: "easy-spaces:health-export:2026-07-28",
    endpoint:
      "POST https://sheets.googleapis.com/v4/spreadsheets/{id}/values/Health!A1:append",
    httpStatus: 429,
    providerResponse: "RESOURCE_EXHAUSTED: quota exceeded for write requests",
    mappingVersion: "v3.4",
    schemaVersion: "2026-06",
    retryPolicy: "Truncated exponential backoff with jitter",
    simulated: true,
    steps: [
      {
        stage: "Build batch",
        status: "Completed",
        timestamp: "9:31:08 AM",
        detail: "12 valid account health rows prepared.",
      },
      {
        stage: "Append values",
        status: "Failed",
        timestamp: "9:31:11 AM",
        detail: "Google Sheets returned HTTP 429.",
      },
      {
        stage: "Schedule retry",
        status: "Scheduled",
        timestamp: "9:31:16 AM",
        detail: "Attempt 2 scheduled after 30 seconds with jitter.",
      },
    ],
  },
  "inc-api-001": {
    correlationId: "corr-sl-c93ab2",
    requestId: "req-01J6API",
    idempotencyKey: "easy-spaces:risk-digest:2026-07-28",
    endpoint: "POST https://slack.com/api/files.upload",
    httpStatus: 200,
    providerResponse: '{"ok":false,"error":"method_deprecated"}',
    mappingVersion: "v1.9",
    schemaVersion: "2026-04",
    retryPolicy: "Blocked until connector patch",
    simulated: true,
    steps: [
      {
        stage: "Create digest",
        status: "Completed",
        timestamp: "9:02:01 AM",
        detail: "CSV prepared for 4 at-risk accounts.",
      },
      {
        stage: "Upload file",
        status: "Failed",
        timestamp: "9:02:04 AM",
        detail: "Slack returned method_deprecated for files.upload.",
      },
      {
        stage: "Post message",
        status: "Blocked",
        timestamp: "9:02:04 AM",
        detail: "The notification was withheld because its attachment failed.",
      },
    ],
  },
};

export const seedInsights: OperationalInsights = {
  failuresAwaitingOwner: 4,
  failuresByType: [
    { label: "Data quality", count: 1 },
    { label: "Authentication", count: 1 },
    { label: "Mapping", count: 1 },
    { label: "Rate limit", count: 1 },
    { label: "Provider change", count: 1 },
  ],
  ownershipQueue: [
    { role: "Customer admin", count: 2 },
    { role: "Integration engineer", count: 2 },
    { role: "System", count: 1 },
  ],
  recoveryMix: [
    { label: "Customer action required", count: 2 },
    { label: "Engineering action required", count: 2 },
    { label: "System managed", count: 1 },
  ],
  humanActionsCompleted: 0,
  systemTransitionsCompleted: 0,
  decisionMetrics: {
    medianTimeToOwnerMinutes: 1.6,
    medianTimeToResolveMinutes: null,
    multiRolePathsObserved: 0,
    systemManagedPaths: 1,
    totalDecisionPaths: 5,
    boundedScopeDecisions: 4,
    excludedFleetPaths: 1,
    guardedDecisions: 1,
    resolvedIncidents: 0,
    containedIncidents: 0,
  },
};

export const mappingRelease = {
  incidentId: "inc-map-001",
  scope: "Easy Spaces / Reservation lifecycle flow",
  rollbackVersion: "v6.0",
  destinationEnum: ["Planning", "Confirmed", "Completed", "Cancelled"],
  cases: [
    ...fixture.salesforce.reservations.map((reservation, index) => ({
      id: `FX-${String(index + 1).padStart(2, "0")}`,
      input: reservation.status,
      expected: "Planning",
      result: "Fail" as const,
      provenance: "Sample data" as const,
    })),
    {
      id: "CT-01",
      input: "Confirmed",
      expected: "Confirmed",
      result: "Pass" as const,
      provenance: "Contract case" as const,
    },
    {
      id: "CT-02",
      input: "Completed",
      expected: "Completed",
      result: "Pass" as const,
      provenance: "Contract case" as const,
    },
    {
      id: "CT-03",
      input: "Cancelled",
      expected: "Cancelled",
      result: "Pass" as const,
      provenance: "Contract case" as const,
    },
    {
      id: "CT-04",
      input: "Unknown",
      expected: "Reject safely",
      result: "Pass" as const,
      provenance: "Contract case" as const,
    },
  ],
};

export const providerContracts = [
  {
    id: "hubspot-openapi",
    provider: "HubSpot",
    title: "HubSpot public API specifications",
    url: "https://github.com/HubSpot/HubSpot-public-api-spec-collection",
    license: "MIT",
    use: "OAuth and CRM contract reference",
  },
  {
    id: "slack-openapi",
    provider: "Slack",
    title: "Slack Web API specifications",
    url: "https://github.com/slackapi/slack-api-specs",
    license: "MIT",
    use: "Provider response and method contract reference",
  },
  {
    id: "slack-files-upload-sunset",
    provider: "Slack",
    title: "Slack files.upload sunset notice",
    url: "https://docs.slack.dev/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay/",
    license: "Official documentation",
    use: "Real provider-change incident",
  },
  {
    id: "google-sheets-limits",
    provider: "Google Sheets",
    title: "Google Sheets API usage limits",
    url: "https://developers.google.com/workspace/sheets/api/limits",
    license: "Official documentation",
    use: "HTTP 429 and exponential-backoff behavior",
  },
  {
    id: "google-sheets-append",
    provider: "Google Sheets",
    title: "spreadsheets.values.append",
    url: "https://developers.google.com/workspace/sheets/api/reference/rest/v4/spreadsheets.values/append",
    license: "Official documentation",
    use: "Export request shape and endpoint reference",
  },
];

export function buildSeedWorkspace(): WorkspaceSnapshot {
  const fleetTenants = structuredClone(seedFleetTenants);
  const connectorDependencies = structuredClone(seedConnectorDependencies);
  const executionEvents = structuredClone(seedExecutionEvents);
  const incidentFingerprints = structuredClone(seedIncidentFingerprints);
  const exposureDecisions = structuredClone(seedExposureDecisions);
  const exposureDecisionHistory = Object.fromEntries(
    Object.entries(exposureDecisions).map(([incidentId, decision]) => [
      incidentId,
      [structuredClone(decision)],
    ]),
  );
  const fleetDecision = exposureDecisions["inc-api-001"];
  const tenantIdsFor = (state: "Affected" | "Exposed" | "Needs review") =>
    fleetDecision.tenantAssessments
      .filter((assessment) => assessment.state === state)
      .map((assessment) => assessment.tenantId);
  const quarantine = structuredClone(seedQuarantineRecords);
  const fleetRelease = structuredClone(seedFleetRelease);
  const jobs = structuredClone(seedJobs);
  const recoveryPlans = buildRecoveryPlans(
    seedIncidents,
    jobs,
    exposureDecisions,
  );
  const activity = structuredClone(seedActivity);
  const insights = structuredClone(seedInsights);
  insights.decisionMetrics = buildRecoveryValueMetrics(
    seedIncidents,
    activity,
    recoveryPlans,
  );
  return {
    tenant: structuredClone(seedTenant),
    fleetTenants,
    fleetIncident: {
      id: "fleet-incident-slack-upload-001",
      title: "Slack file-upload capability retirement",
      provider: fleetDecision.fingerprint.provider,
      connectorFamily: fleetDecision.fingerprint.connectorFamily,
      failureClass: fleetDecision.fingerprint.classification,
      severity: "High",
      recoveryOwner: "Integration engineer",
      communicationOwner: "Support admin",
      actionState: "Contain affected workflows and prepare the connector patch",
      detectedAt: "2026-07-28T16:02:04.000Z",
      acknowledgedAt: null,
      responseDueAt: "2026-07-28T16:45:00.000Z",
      responseSlaStatus: "Due soon",
      affectedTenantIds: tenantIdsFor("Affected"),
      exposedTenantIds: tenantIdsFor("Exposed"),
      needsReviewTenantIds: tenantIdsFor("Needs review"),
      containedTenantIds: [
        ...tenantIdsFor("Affected"),
        ...tenantIdsFor("Exposed"),
      ],
      heldForEvidenceTenantIds: tenantIdsFor("Needs review"),
      status: "Containment active",
      decisionId: fleetDecision.decisionId,
      updatedAt: fleetDecision.createdAt,
      communications: [],
    },
    connectorDependencies,
    evidenceProbes: structuredClone(seedEvidenceProbes),
    executionEvents,
    incidentFingerprints,
    exposureDecisions,
    exposureDecisionHistory,
    recoveryPlans,
    quarantine,
    fleetRelease,
    policyCatalog: structuredClone(recoveryPolicyCatalog),
    scenarioWorker: {
      execution: "Automated demo worker",
      tickIntervalMs: 2500,
      pendingWork: ["Retry Google Sheets export after backoff"],
      nextEligibleAt: null,
    },
    fleetMetrics: buildFleetMetrics(
      jobs,
      quarantine,
      fleetRelease,
      0,
      recoveryPlans["inc-api-001"],
    ),
    accounts: structuredClone(seedAccounts),
    connections: structuredClone(seedConnections),
    flows: structuredClone(seedFlows),
    mappings: structuredClone(seedMappings),
    jobs,
    incidents: structuredClone(seedIncidents),
    supportTasks: structuredClone(seedSupportTasks),
    remediationTasks: [],
    customerCommunications: [],
    activity,
    sources: structuredClone(fixture.sources),
    providerContracts: structuredClone(providerContracts),
    quality: structuredClone(fixture.quality),
    evidence: structuredClone(evidenceByIncidentId),
    traces: structuredClone(traceByIncidentId),
    insights,
    mappingRelease: structuredClone(mappingRelease),
  };
}

export const initialActivity = seedActivity;
